name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # trigger on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js >=22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build React frontend
      - name: Build frontend
        run: npm run build

      # 5️⃣ Deploy to Azure Static Web App
      - name: Deploy to Azure St
